### ISSUE TITLE
Multiple pypi-publish actions triggered when release

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#113]
Creating a new release tag will trigger 3 pypi-publish actions

**Comment by henrymartin1** [comment]
Hm... this is indeed very strange...

**Comment by henrymartin1** [comment]
I had a look at it but like all CI related things it is very hard to debug... I have created a branch and we will have to use it + testpypi to see how it behaves.
It seems like an easy way to fix it would be to add:
```yml
   with:
     skip_existing: true
```
(see [here](https://github.com/pypa/gh-action-pypi-publish/blob/master/README.md#tolerating-release-package-file-duplicates)
but it seems like a hack...

**Comment by henrymartin1** [comment]
The problem was that if the keyword `release` for `on` triggers three runs. If the keyword is `push`. At the same time the line `if: startsWith(github.ref, 'refs/tags')` guarantees that the package is only published if a new tag is pushed. 
I leave this open until the next release when we are sure that it is working correctly.

For debugging I published a few tags on a branch (to test.pypi) until I noticed that this is the same as creating a tag on master. Unfortunately this looks a bit messy now, sorry...

**Comment by henrymartin1** [comment]
The problem did not occur with release 0.5.1 anymore.

**Comment by hong2223** [comment]
can we now delete the `cipypi-publish` branch?

**Comment by henrymartin1** [comment]
👍

**Comment by henrymartin1** [comment]
This should also delete the additional github action
