### ISSUE TITLE
Conventions for missing id linkage

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#118]
Now the `generate_locations` function assign `-1` to `spts` which has no corresponding `location` (default outlier value of dbscan method), but all other generate functions assign `np.nan` to missing linkage. 

Would be nice to change '-1' in the `generate_locations` function.

**Comment by henrymartin1** [comment]
Nice, I stumbled across this as well during the rework of the tripleg generation. I agree. It doesn't matter too much as long as it is consistent. It was -1 in the past because DBSCAN assignes it automatically. We just have to be aware that the ID will become float by doing that but I guess that this is ok.
