### ISSUE TITLE
Model documentation is broken

### ISSUE THREAD

**Issue by henrymartin1** [mie-lab/trackintel#130]
On the Model landing page the documentation of all data types except for tours is broken (meaning missing)

[https://trackintel.readthedocs.io/en/latest/modules/model.html#trackintel.model.triplegs.TriplegsAccessor](https://trackintel.readthedocs.io/en/latest/modules/model.html#trackintel.model.triplegs.TriplegsAccessor)

**Comment by hong2223** [comment]
I had a look at the issue and am afraid that there is no easy way to fix it. The problem is with the `pandas.register_dataframe_accessor` and sphinx simply does not support this type of function in autodoc, see [here](https://pypi.org/project/sphinx-autosummary-accessors/). If I remove the decorator the doc would become normal. 

`autoclass` and `automodule` both won't recognize the class (or recognizes as `alias of pandas.api.extensions.`). What pandas and the `sphinx-autosummary-accessors` do is to write their own templates for generating the document. We can of course do that, but I guess it requires a lot of time.

P.S. tours are working because it is not imported in the __init__.py file (thus not usable outside and in the tests). Interestingly if I remove the other imports, all docstrings except for the first one (no matter which is the first one) will become normal.
