### ISSUE TITLE
temporal tracking quality doesn't work on positionfixes

### ISSUE THREAD

**Issue by svenruf** [mie-lab/trackintel#184]
Should either be implemented or return a correct warning (returns key error 'finished_at' at the moment) and at least be in the documentation of the method.

**Comment by henrymartin1** [comment]
Interesting point, I never thought about using it for positionfixes. I think it is difficult to assess the tracking coverage because positionfixes have no extent meaning. I agree with the fixes you propose.
An idea to assess the quality for positionfixes could be to calculate a histogram of the tracking frequency (would be a different issue).

**Comment by hong2223** [comment]
Thanks for the issue, I will create a pull request adding assertion and docs for positionfixes
