### ISSUE TITLE
TST: Test error 

### ISSUE THREAD

**Issue by hong2223** [mie-lab/trackintel#396]
Our test failed, the error seems to be originated from `sp.as_staypoints.generate_locations()`

**Comment by henrymartin1** [comment]
I have fixed in the issue in PR #397 . The changes were minor but while testing on my local machine I noticed that we trackintel depends strongly on specific packages being up to date. For the CI tests it doesn't really matter because we simply take the newest version. However, for the pip installation it is very important to fix the current version dependencies (e.g., pandas > 1.xxx or geopandas > 1.xxx) in the setup.py. Does anybody have an idea how we should track the version dependencies?

**Comment by henrymartin1** [comment]
@hong2223 Can we close it now?

**Comment by hong2223** [comment]
I though you wanna wait for somebody who has an answer :), otherwise this issue itself is fixed

**Comment by henrymartin1** [comment]
I will open a new issue for this
