### ISSUE TITLE
Error raised in generate_triplegs()

### ISSUE THREAD

**Issue by hanchangyuuu** [mie-lab/trackintel#464]
The following error [ValueError: LineStrings must have at least 2 coordinate tuples] was raised when I ran the code on a dataset of daily human trajectories ;(
![Screenshot 2023-02-13 at 11 35 37](https://user-images.githubusercontent.com/77285494/218435391-ee6ba11e-80ec-44d1-805c-101a0337267d.png)
![Screenshot 2023-02-13 at 11 36 01](https://user-images.githubusercontent.com/77285494/218435475-1dfb3b4c-f0b8-47de-a058-5ce0cb8ff136.png)

**Comment by hong2223** [comment]
Hi,

Thanks for your interest in Trackintel. How do you generate the `sp`? Are you using the `trackintel.preprocessing.positionfixes.generate_staypoints()` with the same pfs `you` used in the screenshot as input?

**Comment by hanchangyuuu** [comment]
Thank you for replying. Yes, I used `trackintel.preprocessing.positionfixes.generate_staypoints()` with the same `pfs` I used in the screenshot as input. The previous steps ran successfully.

<img width="1104" alt="Screenshot 2023-02-13 at 14 36 03" src="https://user-images.githubusercontent.com/77285494/218472330-5af5ea76-a370-4fb6-a591-b064c7cba64e.png">

**Comment by hong2223** [comment]
I suspect this relates to a specific scenario in your data that the algorithm implemented in trackintel cannot handle. Could you try the function with different subsets of your `pfs` and identify which subset the code succeeded/failed?

**Comment by hanchangyuuu** [comment]
OK, I would try with different subsets. Thanks!

**Comment by henrymartin1** [comment]
This looks similar to problems that we had in the past where (usually due to gaps in tracking) there are staypoints that are separated by only 1 positionfix. We introduced the check [here](https://github.com/mie-lab/trackintel/blob/master/trackintel/preprocessing/positionfixes.py#L338) to deal with that but for some cases this seems to fail. 

@hanchangyuuu It would be great if you could provide a small subset of the data that would allow us to reproduce and fix the error.

**Comment by hanchangyuuu** [comment]
I noticed I forgot to reset_index() after preprocessing which caused the problem. Thank you all so much for the explanation!
