### ISSUE TITLE
Question: should we remove asv benchmarking

### ISSUE THREAD

**Issue by bifbof** [mie-lab/trackintel#628]
To be frank it never worked ever since it was implemented and the files it uses are 10 MB big.

**Comment by abcnishant007** [comment]
- I think its not that it never worked. We never ran the benchmarks again. Do you mean that the documentation instructions don't work anymore? pull #183 has the following documentation `ASV-BENCHMARKING.md` at https://github.com/abcnishant007/trackintel/tree/benchmark-files. If this is the case, the documentation can be improved. 
- the files are 10 MB because we had to show the speed improvements for some vectorised operations. We can just keep a sample file and host a bigger file somewhere else for future benchmarks.

Please correct me if I am wrong.
